# Generated by Django 2.2 on 2020-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_userrandommapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='score',
            field=models.CharField(default=0, max_length=900),
        ),
    ]
