# Generated by Django 2.2 on 2020-07-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_registereduser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='score',
            field=models.CharField(max_length=900),
        ),
        migrations.CreateModel(
            name='CompletedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0, max_length=50)),
                ('coins_sent', models.BooleanField(default=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.RegisteredUser')),
            ],
        ),
    ]
